### ISSUE TITLE
Que tal es Flask?

### ISSUE THREAD

**Issue by albertnadal** [gerardgine/fucking-monopoly-bot#1]
https://github.com/gerardgine/fucking-monopoly-bot/blob/bb9528dcaae3195d9a2026819f70fdeb9c167591/commands.py#L1

Sempre havia volgut fer servir Flask per la seva simplicitat a l'anterior feina, però mai en vaig tenir l'oportunitat.

**Comment by gerardgine** [comment]
Aquest és el primer cop que el faig servir, però per fer un servidor per una API és tot súper fàcil. Però vamos, que no tinc massa experiència al respecte. Igual resulta que sota molta càrrega és súper ineficient, o ves a saber. El projecte aquest és un bot de Telegram súper simple, que (imagino) només farem servir amb un grup d'amics quan juguem al Monopoly online.
